Update pubnub and clear logs
resin-io-modules/resin-device-logs pull request #19
Opened 2017-03-07 13:15 UTC by emirotin

**WIP**

2017-03-08 22:38 UTC, emirotin commented
The tests are unstable and new functionality (`clear`) is not covered yet, but the body of the code is OK to review

2017-03-09 06:20 UTC, LucianBuzzo approved these changes
LGTM

2017-03-09 09:48 UTC, emirotin commented
Ah OK seems the windows failure is now the same browser failure (it used to be something different in the node part).

The browser failure is essentially history getting 0 results when it's supposed to get 3.
Will try playing with delays as I don't have any better ideas.

AH, and of course I've tested this by hand in the real UI and it works fine.

2017-03-09 10:44 UTC, pimterry requested changes

2017-03-09 10:44 UTC, pimterry commented on README.md
> +    * [.historyAfterClear(pubnubKeys, device, [options])](#module_logs.historyAfterClear) ⇒ <code>Promise.&lt;Array.&lt;Object&gt;&gt;</code>
`historySinceLastClear` is a clearer method name for this imo (pun intended)

2017-03-09 10:44 UTC, pimterry commented on gulpfile.coffee
> +		.pipe(coffee(bare: true, header: true)).on('error', gutil.log)
:+1:

2017-03-09 10:44 UTC, pimterry commented on lib/logs.coffee
> +	instance.addListener(pubnubListener)
Looks like we no longer subscribe to 'error' here. Is that right?

2017-03-09 10:44 UTC, pimterry commented on lib/utils.coffee
> +	return "device-#{getBaseChannel(device)}-#{suffix}"
We've duplicated this method - it's exactly the same as the method above.

2017-03-09 10:44 UTC, pimterry commented on tests/config.coffee
> +	subscribeKey: 'sub-c-4a67af8a-049f-11e7-b09b-0619f8945a4f'
Is it definitely safe to publish these keys on github?

2017-03-09 12:22 UTC, emirotin commented on README.md
> +    * [.historyAfterClear(pubnubKeys, device, [options])](#module_logs.historyAfterClear) ⇒ <code>Promise.&lt;Array.&lt;Object&gt;&gt;</code>
Right

2017-03-09 12:22 UTC, emirotin commented on lib/utils.coffee
> +	return "device-#{getBaseChannel(device)}-#{suffix}"
Should be already fixed, noticed it myself

2017-03-09 12:23 UTC, emirotin commented on tests/config.coffee
> +	subscribeKey: 'sub-c-4a67af8a-049f-11e7-b09b-0619f8945a4f'
The keys used in production are anyway published to the entire world: https://api.resin.io/config

The channel name itself is here the _secret secret_.

2017-03-09 12:30 UTC, emirotin commented on lib/logs.coffee
> +	instance.addListener(pubnubListener)
Well, I forgot about it but the way to get it has changed. Will include it now

2017-03-09 12:34 UTC, emirotin commented on lib/logs.coffee
> +	instance.addListener(pubnubListener)
Oh wow, there's no way to have it anymore I think. `subscribe` doesn't return a promise.

2017-03-09 12:36 UTC, emirotin commented on lib/utils.coffee
> +	return "device-#{getBaseChannel(device)}-#{suffix}"
Oops wrong. What I've noticed was the duplicate `getBaseChannel`. Looks like I had some buggy local merge.

2017-03-09 15:16 UTC, emirotin commented
Should I just disable the automated browser tests by excluding them from the default `test` script? They run locally and we also test it indirectly in the UI, but they fail consistently in the CI.

2017-03-09 15:19 UTC, pimterry commented on lib/logs.coffee
> +	instance.addListener(pubnubListener)
Really? If you're sure, we should drop it from the docs and examples.

2017-03-09 15:20 UTC, pimterry approved these changes

2017-03-09 15:21 UTC, pimterry commented
I don't think we should disable the tests - we'll forget about them pretty quickly if we do. We should get them fixed, but that doesn't _have_ to block things. If we need this out in time to make the SDK 6.0 release, and we've tested this manually, then I think this is good to merge now, and we can come back and improve the tests later (and it'll be easier to remember to do that if they stay failing).

2017-03-09 15:36 UTC, emirotin commented on lib/logs.coffee
> +	instance.addListener(pubnubListener)
Try for yourself: https://www.pubnub.com/docs/nodejs-javascript/pubnub-javascript-sdk
I didn't find anything related there.

2017-03-09 15:39 UTC, emirotin commented on lib/logs.coffee
> +	instance.addListener(pubnubListener)
Ah, found something: `PNNetworkIssuesCategory` event type can be used in the status callback

2017-03-09 15:39 UTC, emirotin commented on lib/logs.coffee
> +	instance.addListener(pubnubListener)
Will add, though it's hard to test.

2017-03-09 21:19 UTC, merged